version: "3.3"
services:
  server:
    build:
      dockerfile: ./Dockerfile
      context: ./server
    volumes:
      - ./server:/home/node/app
    ports:
      - 3000:3000
    links:
      - db
      - adminer
  mailhog:
    image: mailhog/mailhog
    ports:
      - 9002:8025
  adminer:
    image: adminer
    links:
      - db
    ports:
      - 3010:8080
  db:
    image: mysql:8.0.15
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
        "--sql_mode=",
      ]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: org-erm
      MYSQL_USER: user
      MYSQL_PASSWORD: password
