version: "3.3"
services:
  server:
    build:
      dockerfile: ./Dockerfile
      context: ./server
    volumes:
      - ./server/Org.ERM.WebApi:/app
    ports:
      - 5000:5000
      - 5001:5001
    links:
      - db
      - adminer
    stdin_open: true
    tty: true
  mailhog:
    image: mailhog/mailhog
    ports:
      - 9002:8025
  adminer:
    image: adminer
    links:
      - db
    ports:
      - 3010:8080
  db:
    image: mysql:8.0.15
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
        "--sql_mode=",
      ]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: org-erm
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  # client-web:
  #   build:
  #     dockerfile: ./Dockerfile
  #     context: ./client-web
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./client-web/node_modules:/app/node_modules
  #     - ./client-web:/app
  #   environment:
  #     - NODE_ENV=development
